package SemestralkaTI;

public enum STAV {
	IDLE,
	DEFAULT,
	START,
	NAPOUSTENI_VODY,
	OHRIVANI_VODY,
	MEZI_TOCENIM1,
	MEZI_TOCENIM2,
	VYPOUSTENI_VODY,
	UKONCENI_VYPOUSTENI_VODY,
	PRED_DALSIM_CYKLEM,
	KONEC,
	CHYBA
}